# Generated by Django 4.1.2 on 2022-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Name',
            field=models.CharField(default='apple macbook pro', max_length=20),
            preserve_default=False,
        ),
    ]
