# Generated by Django 4.1.2 on 2022-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgmt', '0002_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetticket',
            name='reason',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetticket',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Opened'), (1, 'Approved'), (2, 'Asset collection'), (3, 'Asset Review'), (4, 'Replaced / Repaired'), (5, 'Verified')], default=0),
        ),
    ]
