# Generated by Django 4.1.2 on 2022-10-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgmt', '0003_assetticket_reason_alter_assetticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetticket',
            name='Asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_mgmt.asset'),
        ),
    ]
