# Generated by Django 4.1.2 on 2022-10-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgmt', '0005_assetticket_damagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetticket',
            name='damagetype',
            field=models.CharField(default='physical', max_length=10),
            preserve_default=False,
        ),
    ]
