# Generated by Django 4.1.2 on 2022-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgmt', '0007_assetticket_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetticket',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Opened'), (1, 'Approved'), (2, 'Asset Review'), (3, 'Replaced / Repaired'), (4, 'Verified')], default=0),
        ),
    ]
