# Generated by Django 4.1.2 on 2022-10-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='parent',
        ),
    ]
