# Generated by Django 4.1.2 on 2022-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_mentor_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='extended_user',
            name='Level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Executive'), (2, 'IT'), (3, 'Employee')], default=3),
        ),
    ]
